# CatCommander Configuration File

[application]
# Application title
title = "CatCommander"
# Window width and height
window_width = 1200
window_height = 800


[ui]
# Theme: "light" or "dark"
theme = "dark"
# Font size for file list
font_size = 12
# Show hidden files by default
show_hidden = false
# Enable dual pane mode
dual_pane = true

[behavior]
# Default sorting: "name", "size", "date", "extension"
default_sort = "name"
# Sort ascending by default
sort_ascending = true
# Follow symbolic links
follow_symlinks = true
# Confirm before delete
confirm_delete = true
# Confirm before overwrite
confirm_overwrite = true

[shortcuts.bindings]
# Keyboard shortcuts mapping operations to keys
# Operations are defined in the Shortcuts enum
#
# Format:
# - Semicolons (;) separate alternative shortcuts for the same operation
# - Commas (,) separate keystrokes in a sequence (e.g., Vim-style chords)
#
# Examples:
#   Single key:              Copy = "F5"
#   Multiple alternatives:   Copy = "F5;Ctrl+C"
#   Keystroke sequence:      Copy = "Ctrl+K,Ctrl+C"
#   Combined:                Copy = "F5;Ctrl+K,Ctrl+C"
Copy = "F5;Ctrl+C"
Move = "F6;Ctrl+X"
Rename = "Shift+F6;F2"
Delete = "F8;Delete"
ExpandCurrentFolder = "Right"
ExpandSelectedFolders = "Ctrl+Right"
GoIntoCurrentFolder = "Enter;Ctrl+Down"
GoBackToParentFolder = "Backspace;Ctrl+Up"
GotoFirstItem = "Home;Ctrl+Home"
GotoLastItem = "End;Ctrl+End"

[logging]
# Log level: "trace", "debug", "info", "warn", "error"
level = "info"
# Log file path (relative to application directory)
log_file = "logs/catcommander.log"

